name: "Assign PR template based on contributor type"

on:
  pull_request:
    types: [opened]

jobs:
  choose-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine if PR author is org member
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const baseOwner = context.payload.pull_request.base.repo.owner.login;
              await github.rest.orgs.checkMembershipForUser({
                org: baseOwner,
                username: context.actor
              });
              return true;
            } catch {
              return false;
            }

      - name: Load appropriate template
        id: template
        run: |
          if [ "${{ steps.check.outputs.result }}" = "false" ]; then
            cp .github/PULL_REQUEST_TEMPLATE_EXTERNAL.md pr-body.md
          fi

      - name: Update PR body
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('pr-body.md')) {
              const body = fs.readFileSync('pr-body.md', 'utf8');
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                body
              });
            }